package letitout

import (
	"encoding/base64"
	"log"
	"strings"
)

func base64Decode() string {
	str := "4pmqIFBhaW50IG5vIGlsbHVzaW9uLCB0cnkgdG8gY2xpY2sgd2l0aCB3aGF0Y2hhIGdvdCDimaoK4pmqIFRhc3RlIGV2ZXJ5IHBvdGlvbiAnY2F1c2UgaWYgeWVyIGxpa2UgeWVyc2VsZiBhIGxvdCDimaoK4pmqIEdvIGxldCBpdCBvdXQsIGdvIGxldCBpdCBpbiwgZ28gbGV0IGl0IG91dCDimaoK4pmqIExpZmUgaXMgcHJlY29jaW91cyBpbiBhIG1vc3QgcGVjdWxpYXIgd2F5IOKZqgrimaogU2lzdGVyIHBzeWNob3NpcyBkb24ndCBnb3QgYSBsb3QgdG8gc2F5IOKZqgrimaogU2hlIGdvIGxldCBpdCBvdXQsIHNoZSBnbyBsZXQgaXQgaW4sIHNoZSBnbyBsZXQgaXQgb3V0IOKZqgrimaogU2hlIGdvIGxldCBpdCBvdXQsIHNoZSBnbyBsZXQgaXQgaW4sIHNoZSBnbyBsZXQgaXQgb3V0IOKZqgrimaogSXMgaXQgYW55IHdvbmRlciB3aHkgUHJpbmNlcyAmIEtpbmdzIOKZqgrimaogQXJlIGNsb3ducyB0aGF0IGNhcGVyIGluIHRoZWlyIHNhd2R1c3QgcmluZ3Mg4pmqCuKZqiBPcmRpbmFyeSBwZW9wbGUgdGhhdCBhcmUgbGlrZSB5b3UgYW5kIG1lIOKZqgrimaogV2UncmUgdGhlIGtlZXBlcnMgb2YgdGhlaXIgZGVzdGlueSwg4pmqCuKZqiBXZSdyZSB0aGUga2VlcGVycyBvZiB0aGVpciBkZXN0aW55IOKZqgrimaogSSdtIGdvaW4nIGxlYXZpbmcgdGhpcyBjaXR5LCBJJ20gZ29pbicgZHJpdmluJyBvdXR0YSB0b3duIOKZqgrimaogQW5kIHlvdXIgY29taW4nIHdpdGggbWUgdGhlIHJpZ2h0IHRpbWUgaXMgYWx3YXlzIG5vdyDimaoK4pmqIFRvIGdvIGxldCBpdCBvdXQsIHRvIGdvIGxldCBpdCBpbiwgYW5kIGdvIGxldCBpdCBvdXQg4pmqCuKZqiBUbyBnbyBsZXQgaXQgb3V0LCB0byBnbyBsZXQgaXQgaW4sIGFuZCBnbyBsZXQgaXQgb3V0IOKZqgrimaogSXMgaXQgYW55IHdvbmRlciB3aHkgUHJpbmNlcyBhbmQgS2luZ3Mg4pmqCuKZqiBBcmUgY2xvd25zIHRoYXQgY2FwZXIgaW4gdGhlaXIgc2F3ZHVzdCByaW5ncyDimaoK4pmqIE9yZGluYXJ5IHBlb3BsZSB0aGF0IGFyZSBsaWtlIHlvdSBhbmQgbWUg4pmqCuKZqiBXZSdyZSB0aGUgYnVpbGRlcnMgb2YgdGhlaXIgZGVzdGlueSDimaoK4pmqIFdlJ3JlIHRoZSBidWlsZGVycyBvZiB0aGVpciBkZXN0aW55IOKZqgrimaogV2UncmUgdGhlIGJ1aWxkZXJzIG9mIHRoZWlyIGRlc3Rpbnkg4pmqCuKZqiBXZSdyZSB0aGUgYnVpbGRlcnMgb2YgdGhlaXIgZGVzdGlueSDimaoK4pmqIFNvIGdvIGxldCBpdCBvdXQsIGdvIGxldCBpdCBpbiDimaoK4pmqIEdvIGxldCBpdCBvdXQsIGRvbid0IGxldCBpdCBpbiDimaoK4pmqIEdvIGxldCBpdCBvdXQsIGdvIGxldCBpdCBpbiDimaoK4pmqIEdvIGxldCBpdCBvdXQsIGRvbid0IGxldCBpdCwgZG9uJ3QgbGV0IGl0IGluLCBkb24ndCBsZXQgaXQgaW4g4pmq"
	data, err := base64.StdEncoding.DecodeString(str)

	if err != nil {
		log.Fatal("Error:", err)
	}

	return string(data)
}

func GetLine() func() string {
	i := 0
	lines := strings.Split(base64Decode(), "\n")

	return func() string {
		if i != len(lines) {
			nextLine := lines[i]

			i++
			return nextLine
		}

		return ""
	}
}
